"""Add world models and basemap georeferencing

Revision ID: d31c563b5509
Revises: custom_basemaps_001
Create Date: 2025-06-23 16:35:40.472638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd31c563b5509'
down_revision: Union[str, None] = 'custom_basemaps_001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('world_models',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('planet_scale_factor', sa.Float(), nullable=True),
    sa.Column('extent_bounds', sa.ARRAY(sa.Float()), nullable=True),
    sa.Column('crs_definition', sa.Text(), nullable=True),
    sa.Column('transformation_matrix', sa.ARRAY(sa.Float()), nullable=True),
    sa.Column('default_center', sa.ARRAY(sa.Float()), nullable=True),
    sa.Column('default_zoom', sa.Integer(), nullable=True),
    sa.Column('earth_radius', sa.Float(), nullable=True),
    sa.Column('coordinate_system_notes', sa.Text(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('owner_uuid', sa.UUID(), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('custom_basemaps', sa.Column('world_model_id', sa.String(length=12), nullable=True))
    op.add_column('custom_basemaps', sa.Column('georeferencing_points', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('custom_basemaps', sa.Column('transform_matrix', sa.ARRAY(sa.Float()), nullable=True))
    op.drop_index(op.f('idx_custom_basemaps_owner'), table_name='custom_basemaps')
    op.drop_index(op.f('idx_custom_basemaps_public'), table_name='custom_basemaps')
    op.create_foreign_key(None, 'custom_basemaps', 'world_models', ['world_model_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'custom_basemaps', type_='foreignkey')
    op.create_index(op.f('idx_custom_basemaps_public'), 'custom_basemaps', ['is_public'], unique=False)
    op.create_index(op.f('idx_custom_basemaps_owner'), 'custom_basemaps', ['owner_uuid'], unique=False)
    op.drop_column('custom_basemaps', 'transform_matrix')
    op.drop_column('custom_basemaps', 'georeferencing_points')
    op.drop_column('custom_basemaps', 'world_model_id')
    op.drop_table('world_models')
    # ### end Alembic commands ###